CREATE USER 'dev'@'%' IDENTIFIED BY "test";

REVOKE ALL PRIVILEGES ON *.* FROM 'dev'@'%';
GRANT SELECT on RFID.* TO 'dev'@'%';

FLUSH PRIVILEGES;

DROP USER 'dev'@'%';

FLUSH PRIVILEGES;


DROP USER IF EXISTS 'rfid'@'%';

CREATE USER 'rfid'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
REVOKE ALL PRIVILEGES ON *.* FROM 'rfid'@'%';
FLUSH PRIVILEGES;
GRANT ALL ON RFID.* TO 'rfid'@'%';
FLUSH PRIVILEGES;



